### ISSUE TITLE
Building dependencies within a PR

### ISSUE THREAD

**Issue by daler** [bioconda/recipes#102]
It would be nice to avoid the PR -> test -> merge -> test cycle when building dependencies, and instead submit all dependencies simultaneously and have the new toposort stuff in #93 sort out the build order.

I think it would work -- but only when testing on the master branch on travis-ci -- if we move the uploading block in `build-packages.py` to within the `build_recipe()` function. That is, each dependency recipe will be immediately uploaded to the bioconda channel, ready for use in subsequent recipes.

But of course this doesn't work when testing locally or while testing a PR since nothing gets uploaded. While `conda install` has a `--use-local` option, there's no such option for `conda build`.  The closest is I can find is indexing a local channel, documented [here](http://conda.pydata.org/docs/custom-channels.html).

Maybe when testing locally or in a PR we can just install each package immediately after building? Any other ideas?

**Comment by johanneskoester** [comment]
Yes, actually that was my intention, and I thought that conda build will use locally built packages.
Are you sure that it does not work like that?

**Comment by daler** [comment]
Finally got this working in #149.

Some notes for future reference:

- linux recipes are built in a docker container specified in `Dockerfile`; osx recipes are built in the travis-ci environment built by `travis-setup.sh`
- `build-packages.py` is used in both environments, so the path to anaconda has to be the same in both environments
- *Installing* from locally-built package works by default, but *building* does not use locally-built packages by default. The local channel had to be explicitly added. 
- In order for this to work, `conda index` needs to be run on the channel after every build, on each platform's subdirectory


So:

- `Dockerfile` and `travis-setup.sh` both use `/anaconda` as the installation path
-  `build-packages.py` calls `conda index` right before every build
- Johannes added dependency sorting to set the build order
- As a demo, #150 was a single pull request with multiple dependencies. These were built in the right order, and the PR passed.
