### ISSUE TITLE
Add flask requirement to snakemake recipe?

### ISSUE THREAD

**Issue by kyleabeauchamp** [bioconda/recipes#145]
Given that there is a Continuum provided flask package for conda (http://docs.continuum.io/anaconda/pkg-docs), IMHO there's no downside to including flask as a run requirement for snakemake.  Might be good to add this because the HTML viewer looks pretty nice.

**Comment by kyleabeauchamp** [comment]
Actually it seems like I can get the same info from the commandline, so I guess this would really depend on whether the HTML gui is a widely used feature worth having "batteries included".

**Comment by johanneskoester** [comment]
Indeed, the gui is not that widely used. So I'd rather keep it optional I think.
