### ISSUE TITLE
requirements from custom channels

### ISSUE THREAD

**Issue by dkoppstein** [bioconda/recipes#171]
Hi, I was trying to create a recipe for [MiGMAP](https://github.com/mikessh/migmap) which is relevant to my work. However, it seems like I have run into conda/conda#1504 which is that I require a certain version of java-jre to run the package. This package is available on anaconda.org but only in a custom channel, cyclus. Do you guys have an idea of a workaround to specify a package from a specific channel as a requirement for another package? See also conda/conda-build#532.

**Comment by dkoppstein** [comment]
conda/conda-build#532

**Comment by johanneskoester** [comment]
We have basically a copy of that package in bioconda: java-jdk. The only difference is that we use the zulu build. Does depending on that work for you?

**Comment by johanneskoester** [comment]
So far, apart from the r channel, we don't depend on external channels, and if possible I would like to keep it that way, because we can never know what happens to these channels.

**Comment by dkoppstein** [comment]
Yes, that package works for me. I'm running into another issue, which I've described further in [this PR](https://github.com/bioconda/recipes/pull/172) (which is failing at the moment). But I'll close this issue. Thanks!
