### ISSUE TITLE
Kallisto not running

### ISSUE THREAD

**Issue by johanneskoester** [bioconda/recipes#2]
Currently, the kallisto recipe fails the test with the following error:

```
kallisto: /home/koester/miniconda3/envs/_test/bin/../lib/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by kallisto)
kallisto: /home/koester/miniconda3/envs/_test/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by kallisto)
```

**Comment by chapmanb** [comment]
I pushed a new Kallisto package built on CentOS5 that avoids this problem (more details athttps://github.com/bioconda/recipes/issues/1#issuecomment-143478351)
