### ISSUE TITLE
Avoiding using Java as a run dependency

### ISSUE THREAD

**Issue by chapmanb** [bioconda/recipes#200]
The snpEff recipe @tomkinsc created is great, and I'd love to include it in our installations but I'm a bit worried about the Java dependency. It's pretty heavy-weight and also introduces Java 8 into the environment which can create issues with tools like GATK that only support older Java versions.

Could we leave Java as something that we assume exists in the base system (or allow users to manually install it via conda)? What does everyone think?

**Comment by dkoppstein** [comment]
Hi, I ran into a similar issue when creating a recipe for MiGMAP, which requires Java 8. I agree it's heavy-weight, but I think it might be better than producing a package which will only run on some architectures, so I put the Java runtime dependency in the recipe. 

Is it acceptable to run GATK and snpEff in separate environments? More generally, it seems like multiple environments might be required to deal with these cases when you have incompatibilities with core system binaries. For my pipeline, I have some packages that haven't been ported yet to Python 3, so I have two environments for Python 2 and Python 3. Maybe there needs to be some way to specify the meta-environment.

**Comment by johanneskoester** [comment]
There are also opposite cases. Yesterday, a colleague wanted to use fastqc on a server that only had an old java version. It crashed silently without an error. I have fixed this by adding our java-jdk package as a dependency to the fastqc recipe.

We can add a Java 7 build. As long as recipes don't require a specific version, conda will be able to sort out which one should be used. I think it is an important property of bioconda to give in a sense a guarantee that packages will work independent of the system. When relying on the system Java, we abandon this.

And we should definitely try to get GATK included into Bioconda. @tomkinsc, do you have contact the Geraldine or whoever of the GATK people would be a good person to talk to about this?

**Comment by tomkinsc** [comment]
@johanneskoester The official stance is probably to contact softwarelicensing@broadinstitute.org. The dual license (free for academic use, fee for commercial use) makes it a challenge. As you probably know, currently to acquire GATK you have to log in to the GATK website and agree to the license to download a copy. I wonder if there might be a way to do an interactive conda install, where you provide your GATK login credentials as part of the install process, along with assent of the license (similar to how Xcode asks about its license agreement from the command line). I suppose the recipe could install a script that prompts for the GATK forum credentials and then tries to download the package. I'm outside the GATK group, but Eric Banks (ebanks@) may be the person to contact. If not about including GATK directly, perhaps about a workaround or a way to make it available through conda via approved credentials of some kind.

**Comment by johanneskoester** [comment]
Thanks for the info Chris. Another option would be to wait until Bioconda is so big that the GATK guys are changing their license for us ;-). No, seriously, I would not that much like the download option, but maybe we can come to some agreement.

**Comment by tomkinsc** [comment]
Yeah, it would definitely be better if GATK were under a free license, but I guess we have to fund the team of people upstairs at the Broad somehow. I personally wish GATK-lite were still around.

**Comment by chapmanb** [comment]
Thanks for the feedback. It sounds like I'm outvoted so no worries. I can remove java-jdk after install and use the system java in my scripts and will approach it that way for now.

For GATK, I also had a conversation with Geraldine about making it re-distributable but I don't think they've made any license changes. I have a command line shell wrapper around the MIT-licensed parts of GATK (https://github.com/chapmanb/gatk) which I could include as a recipe. This doesn't include variant calling and other restricted walkers, but does have a lot of useful functionality for manipulating VCF files.

**Comment by johanneskoester** [comment]
In fact, this is a nice example why we might want to support multiple versions sometimes. If GATK needs an old java, we can support this as well, e.g. it is straightforward to have the same recipe for the JDK 7 distribution of Zulu (see [here](http://www.azul.com/downloads/zulu/zulu-linux/)).

**Comment by johanneskoester** [comment]
Adding the GATK lite recipe for now sounds good.

**Comment by chapmanb** [comment]
Thanks for all the thoughts. I added the GATK framework package without an explicit java dependency for now and we can clean this up with regards to multiple versions once that is all in place. Thanks again for the discussion.
