### ISSUE TITLE
Packages are being built on ubuntu 14.04?

### ISSUE THREAD

**Issue by ostrokach** [bioconda/recipes#223]
I think there's something weird going on, with at least some of the packages being tested and built using Ubuntu 14.04 rather than CentOS 5. 

For example, [here](https://travis-ci.org/bioconda/recipes/jobs/88930783) is the travis.ci logs for `tmux`, which show that it's being tested on Ubuntu 14.04 (`gcc (Ubuntu 4.8.4-2ubuntu1~14.04) 4.8.4`). And the binary that got pushed to anaconda.org is incompatible with CentOS 5 or 6 (it throws a GLIBC 2.14 error). 

From what I understand, every package should be tested and built using the CentOS 5 docker container?

Also, is it possible to build both the Python 3.4 and Python 3.5 packages for the time being? Right now some packages in the repository were build using 3.4 and some using 3.5, which causes incompatibilities.

**Comment by johanneskoester** [comment]
Hi,
that gcc logging entry is from the underlying travis machine. After that, the build command is started from the docker container (by the script travis-run.sh). So, it definitely runs on CentOS 5. No idea what causes the GLIBC error. Did you try to build locally with the docker container? Does that cause the same problem?

I think we should rebuild everything for Python 3.5 then. I would have thought that our build script automatically rebuilds packages that are not already available for 3.5. Can you provide an example?

**Comment by ostrokach** [comment]
Hey,

I haven't figured it out, but something weird is going on. If I run `ldd --version` inside a local docker container, it gives me `ldd (GNU libc) 2.5`, as expected for CentOS 5. However, the docker container that runs on Travis somehow uses a different glibc. 

I created a small package to test this: `test-glibc`. During the build process, it saves the output of `ldd --version` to the `test-glibc.sh` binary. If you install the package and run `test-glibc.sh`, it prints out: `ldd (Ubuntu EGLIBC 2.19-0ubuntu6.6) 2.19`, so the package was build on Ubuntu 14.04.

Consistent with this, packages such as `cd-hit` (not mine) and `tmux` (mine) throw an error when run inside CentOS 6:

    cd-hit: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by cd-hit)

**Comment by johanneskoester** [comment]
Indeed, this is weird. I have no explanation... Anybody else?

**Comment by johanneskoester** [comment]
Hi again. I have extended the output of the build script. It now also prints ldd --version and gcc --version immediately before starting the builds.
As you can see [here](https://travis-ci.org/bioconda/recipes/jobs/90097209), versions are as expected on CentOS 5...

When I install test-glibc from the bioconda channel, I get this output:

```
ldd (GNU libc) 2.5
Copyright (C) 2006 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```

I guess you accidentally tested a locally built version.
cd-hit was added pretty early I think. Maybe it was not built yet with CentOS? For tmux, please make sure that the source does not contain precompiled binaries.

**Comment by ostrokach** [comment]
Hmm, you are right. It does say `ldd (GNU libc) 2.5`, and the new cd-hit that you built works. 
I must be screwing something up on my end.

Thanks a lot for your help!

**Comment by johanneskoester** [comment]
You're welcome!
