### ISSUE TITLE
Funding

### ISSUE THREAD

**Issue by johanneskoester** [bioconda/recipes#245]
We are now using 2GB of the 3GB storage we get for free on Anaconda.org. This means that we might need to buy an Organization plan for $49 per month. This issue is intended to discuss funding possibilities. Before trying anything else, I think we could contact Continuum Analytics. Bioconda is growing fast and shoud be a huge selling point for conda in our field. Hence, it might be that they grant us some discount if we ask.
We could write a letter together, to give it the weight of all our affiliations. If you agree, I would start working on a draft.

**Comment by ostrokach** [comment]
A letter sounds like a good idea. 
Let me know how I can help.

**Comment by chapmanb** [comment]
Happy to help as well. Thanks for leading this.

**Comment by acaprez** [comment]
I'd be happy to be involved as well.

**Comment by daler** [comment]
Count me in, too.

**Comment by dkoppstein** [comment]
Sounds great, happy to help as well! In case this falls through, perhaps we could also try reaching out to the Open Bioinformatics Foundation, but I agree it would be a huge selling point for Conda so hopefully the folks at Continuum will agree to increase our storage limit.

**Comment by johanneskoester** [comment]
Hi guys,
I have created a first draft [here](https://github.com/bioconda/recipes/wiki/Letter-to-CA). Feel free to edit or comment!

**Comment by chapmanb** [comment]
Johannes -- this looks great, thanks for putting it together. My only suggestion was that it might be a little formal with `Madams and Sirs` but maybe that's not a bad thing. Otherwise feel free to send out and let us know how it goes. Thanks again.

**Comment by johanneskoester** [comment]
Thanks, I have made it a bit less formal and just sent the email. Fingers crossed!

**Comment by johanneskoester** [comment]
Hi guys!  
Very good news! Continuum Analytics gives us a **free** organization plan with 100GB storage. That should be enough for the next years! Thanks for your help and advice!

**Comment by chapmanb** [comment]
Johannes -- congrats. Great work putting this all together and thanks to Continuum for the generosity.

**Comment by daler** [comment]
Great news!

**Comment by dkoppstein** [comment]
Congrats!
