### ISSUE TITLE
new docker image build?

### ISSUE THREAD

**Issue by tomkinsc** [bioconda/recipes#25]
I made a small change (09968c673545d42520940aaf9e0c63b3a03391d4) to the Dockerfile to set the LANG environment variable to UTF-8.

Would it be possible to build the Dockerfile and submit the new version to the Docker Hub?

**Comment by johanneskoester** [comment]
I have set up automated builds from master. The container should be updated now.

**Comment by tomkinsc** [comment]
Even better! Thank you.
