### ISSUE TITLE
Travis-CI build reports success if Anaconda upload times out

### ISSUE THREAD

**Issue by acaprez** [bioconda/recipes#261]
Just wanted to let folks know of an issue I saw after merging htseq into master.  During the Travis-CI build to upload the package, the connection to anaconda.org timed out for some reason.  The build still exited with 0 status though, so to Travis it was marked as succeeded.  This caused the package info to be created on the bioconda channel with no actual files attached.  I re-ran the Travis build and it succeeded the second time, but it might be nice to make the build script a bit more stringent on catching exceptions and such.  I attached the Travis-CI log from the first build if anyone would like to look at it.

[travisci_log.txt](https://github.com/bioconda/recipes/files/34462/travisci_log.txt)

**Comment by johanneskoester** [comment]
I think I have fixed this in pull request #270.

**Comment by johanneskoester** [comment]
Thanks!
