### ISSUE TITLE
install X11 on docker container?

### ISSUE THREAD

**Issue by daler** [bioconda/recipes#266]
Often the test portion of a recipe, at least for a Python package, tries to import the module. If the module happens to have the canonical `from matplotlib import pyplot as plt` (for example the `seaborn` package does this) then the recipe will fail.

Specifically:
```bash
docker run -it --entrypoint=/bin/bash bioconda/bioconda-builder

# in the container:
conda install -y matplotlib
python -c 'from matplotlib import pyplot'
```
gives the error:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/anaconda/lib/python3.5/site-packages/matplotlib/pyplot.py", line 114, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/anaconda/lib/python3.5/site-packages/matplotlib/backends/__init__.py", line 32, in pylab_setup
    globals(),locals(),[backend_name],0)
  File "/anaconda/lib/python3.5/site-packages/matplotlib/backends/backend_qt4agg.py", line 18, in <module>
    from .backend_qt5agg import FigureCanvasQTAggBase as _FigureCanvasQTAggBase
  File "/anaconda/lib/python3.5/site-packages/matplotlib/backends/backend_qt5agg.py", line 15, in <module>
    from .backend_qt5 import QtCore
  File "/anaconda/lib/python3.5/site-packages/matplotlib/backends/backend_qt5.py", line 31, in <module>
    from .qt_compat import QtCore, QtGui, QtWidgets, _getSaveFileName, __version__
  File "/anaconda/lib/python3.5/site-packages/matplotlib/backends/qt_compat.py", line 124, in <module>
    from PyQt4 import QtCore, QtGui
ImportError: libXext.so.6: cannot open shared object file: No such file or directory
```

The best solution I've found is in the container:

```
yum install xorg-x11-apps
```

Do you think this is worth adding to the image?

**Comment by johanneskoester** [comment]
Yes, that's a good idea. Feel free to do that!

**Comment by daler** [comment]
OK -- X11 is now in the image as of #269

**Comment by sebastian-luna-valero** [comment]
Hello,

I am facing this problem now with the `conda-forge` docker image:
https://github.com/bioconda/bioconda-recipes/blob/master/config.yml#L6

when I run `simulate-travis.py` the errors are:
```
SERR from PyQt4 import QtCore, QtGui
SERR ImportError: libXext.so.6: cannot open shared object file: No such file or directory
```

I am confused, as `libXext-devel` is installed on the `conda-forge` image:
https://github.com/conda-forge/docker-images/blob/master/linux-anvil/Dockerfile#L24

since they discussed it in the past:
https://github.com/conda-forge/docker-images/issues/1

Any ideas why this is happening?

Many thanks,
Sebastian

**Comment by bgruening** [comment]
Unfortunately, this dependency is indeed in this container ... it should not be because this assumption is often not valid on HPC environments. In bioconda we are more strict an test against a busybox Docker container without X. This means your tool fails at this step. If you depend on `xorg-libxext` it should solve your problem hopefully.

**Comment by sebastian-luna-valero** [comment]
Thanks @bgruening 

This is a python package doing:
```
SERR import matplotlib.pyplot as plt
```
and it depends on `libXext`:
```
libXext-1.3.3-1.el6.x86_64 : X.Org X11 libXext runtime library
Repo        : installed
Matched from:
Filename    : /usr/lib64/libXext.so.6.4.0
Filename    : /usr/lib64/libXext.so.6
```

Actually, I am just updating an existing recipe:
https://github.com/bioconda/bioconda-recipes/tree/master/recipes/cgat-report

We use `Xvfb` or `X virtual framebuffer` (`xorg-x11-server-Xvfb-1.17.4-9.5.el6_8.x86_64.rpm`) in our cluster nodes without X. Would this be a solution?

Please let me know your thoughts.

**Comment by cokelaer** [comment]
For your information, I have the same problem with another recipes, which was working fine (biokit 0.2). When I tried to update in the last days, I got this related error message:

    SERR from PyQt4 import QtCore, QtGui

Whereas I'm using matplotlib 2.0 (qt5 I believe).

**Comment by bgruening** [comment]
Have you declared a dependency on qt4?

**Comment by cokelaer** [comment]
Not specifically since I'm guessing it is part of matplotlib or pandas recipes's responsability ?

**Comment by bgruening** [comment]
Mh, indeed: https://github.com/conda-forge/matplotlib-feedstock/blob/master/recipe/meta.yaml#L59
Can you check that you get this package?

**Comment by cokelaer** [comment]
I see. Well, I update the recipes and see the results. This may take a while to get the results (probably tomorrow) and let you know the outcome. thanks.

**Comment by cokelaer** [comment]
Without a pin on qt, I got the error mentionned above (pyqt4) and pinning qt to 4.11.* as in the matplotlib recipe from conda-forge (https://github.com/conda-forge/matplotlib-feedstock/blob/master/recipe/meta.yaml#L59) I got this new error:
```[Feb 21 14:49:10] SERR ImportError: libstdc++.so.6: cannot open shared object file: No such file or 
directory```
on https://travis-ci.org/bioconda/bioconda-recipes/jobs/203819686 

Maybe that is a different problem and I can open a new issue ?

**Comment by bgruening** [comment]
Oh yes it is and looks good, as I have at least an idea. Can you please add libgcc to your runtime deps.
