### ISSUE TITLE
Building python2.7 packages only

### ISSUE THREAD

**Issue by percyfal** [bioconda/recipes#38]
Hi,

I'm setting up a recipe for MACS2.1.0 which *requires* python 2.7 to run. The only meta configuration that works is to set python ==2.7.X (some specific version) - setting >=2.7 will obviously spill over to python 3. I also tried [selectors](http://conda.pydata.org/docs/building/meta-yaml.html#preprocessing-selectors) but to no avail. I've been scouring through the conda docs as well as conda recipes at anaconda but I can't find any mention of this setting. Does anyone have a quick answer to this one?

**Comment by johanneskoester** [comment]
I think just saying =2 or something like that should work (at least for our setting). We won't build with lower versions and there won't be any releases beyond 2.7.x in the Python 2 branch.

**Comment by percyfal** [comment]
Unfortunately neither =2 nor =2.7 work:

Error: Did not recognize version specification: '=2'

IOW, it seems as if specific version is required. MACS2 suggests 2.7.2 but that version doesn't seem to work, 2.7.10 does. I'll settle for the latter unless there are any objections.

**Comment by johanneskoester** [comment]
What about ``python ==2.7.*``. SHould work according to the docs:
http://conda.pydata.org/docs/spec.html#package-match-specifications

**Comment by percyfal** [comment]
No, but     - python >=2.7,<3 seems to do the trick! My scouring of the documentation was apperently quite cursory... Thanks!
