### ISSUE TITLE
Build packages

### ISSUE THREAD

**Issue by johanneskoester** [bioconda/recipes#4]
Hi Hyeshik,
nice work with the new packages! Are you able to build and upload them, or do you want me to do that? We could also try to setup the anaconda build service for linux-64, but so far I did no manage to connect it with github...

**Comment by daler** [comment]
Hi Johannes & Hyeshik - 

I built my packages locally, but am unable to upload to the bioconda channel. The only solution I was able to find for organizations was in [this post](https://groups.google.com/a/continuum.io/forum/#!topic/conda/uYtVRGW--iU), but 

```
anaconda upload -u bioconda anaconda2/conda-bld/linux-64/subread-1.4.6p5-0.tar.bz
```

gives me the error `[BinstarError] Can not create package`.

Have either of you had luck uploading to the bioconda organization?

**Comment by johanneskoester** [comment]
Hi Ryan,
I do that all the time. I have changed your rights to admin. Does it work now?

**Comment by daler** [comment]
Hmm, still not working for me.  I made my own test organization and was able to successfully upload a new package to it, so it seems like things are configured correctly on my machine, at least for organizations created by my user name.  

I added you as a user with "owner" rights to that new organization, which is unoriginally named "temp" . . . are you able to upload packages there?

**Comment by johanneskoester** [comment]
Yes, I can upload there...
I have moved you to the owners group. Does it work now?

**Comment by daler** [comment]
Yep, now it works. Thanks!

**Comment by hyeshik** [comment]
I was trying to figure out how to upload the package. I just successfully finishing uploading my packages. Thank you!
