### ISSUE TITLE
Determine proper order of builds in build-packages

### ISSUE THREAD

**Issue by johanneskoester** [bioconda/recipes#93]
Inspired by pull request #92, I think we can come up with a modification of build-packages.py, that parses the build requirements and uses them to determine a DAG of build jobs where the edges represent dependencies.
Then, the proper order of build jobs such that a package is built after all its dependencies have been built can be determined by traversing the DAG in breadth or depth-first order starting from root nodes.

What do you think?

**Comment by daler** [comment]
Sounds great!

My solution was a quick hack just to make managing the bioconductor update easier on my end. I suspect the best way to handle this would be to use `conda` itself to solve dependencies. I couldn't find anything exposed to the conda CLI, and it was easier to roll my own than dig through conda's API.

**Comment by kyleabeauchamp** [comment]
We have some functionality for this elsewhere.  Not sure if it's helpful, though, as you already rolled your own for the bioconductor stuff.  Link below.

https://github.com/omnia-md/conda-recipes/blob/master/conda-build-all

**Comment by johanneskoester** [comment]
Thanks for the link. This is very much in the needed direction. I have started to port the idea to our build-packages.py script. Looks like if you only need the sorting and use some external dependencies, it boils down to adding just a few lines. You can find the current status in pull request #98.

**Comment by johanneskoester** [comment]
Implementation works now.
